/* #undef ENABLE_BITMAP_ALLOCATOR */
/* #undef ENABLE_BOOST_FAST_POOL_ALLOCATOR */
/* #undef ENABLE_BOOST_POOL_ALLOCATOR */
/* #undef ENABLE_DEBUG_ALLOCATOR */
/* #undef ENABLE_MT_ALLOCATOR */
/* #undef ENABLE_NEW_ALLOCATOR */
/* #undef ENABLE_POOL_ALLOCATOR */
/* #undef ENABLE_TBB_ALLOCATOR */
/* #undef HAVE_ALLOCATOR_CONFIG */
#define HAVE_BOOST_SHARED_PTR 1
/* #undef HAVE_STD_SHARED_PTR */
#define HAVE_STD_TR1_SHARED_PTR 1
#define HAVE_BOOST 1
#define HAVE_BOOST_SHARED_PTR 1
#define HAVE_TBB 1
#define HAVE_SSL 1
/* #undef HAVE_EMX */
/* #undef HAVE_VMA */
/* #undef HAVE_SYSTEMTAP */
/* #undef HAVE_STD_UNIQUE_PTR */
/* #undef ENABLE_SSO */
/* #undef ENABLE_THROW_DECL */
/* #undef ENABLE_FLAT_FIELDMAP */
/* #undef ENABLE_RELAXED_ORDERING */
/* #undef ENABLE_DICTIONARY_FIELD_ORDER */
